public class CheckDataTypesAssignment3 {
    public void MethodBoolean(){
        Boolean checkBoolean = true;
        system.debug('I m checking boolean: ' + checkBoolean);
    }
    public void MethodInteger(){
        Integer varfirst = 1;
        Integer varsecond = 2;
        system.debug(varfirst + ',' + varsecond);
    }
    public void StringMethod(){
        String varname = 'Name';
        String var2name = 'Şevval';
        system.debug(varname + ' ' + var2name);
    }
}
